export const colors = {
  primary: '#ee4e0f',
  secondary: '#ffaa50',
  primaryLight: '#ffd19f',
  background: '#f2f2f2',
  textPrimary: '#161616',
  textSecondary: '#666',
  border: '#ccc',
  white: '#fff',
  black: '#000',
  green: '#4CAF50',
  heart: '#ff6b81',
  headerBackground: "#ffe1a2",
  cardBackground: '#fbfbfb',
  secondaryBackground: '#ddd',
  settingsText: '#67676a',
};
